version: '3'
services:
  mwc:
    build:
      context: .
      dockerfile: Dockerfile
    image: mwc
    volumes:
      - .:/usr/src/app/MovieWordCloud
    env_file: configuration.env
    links:
      - database
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_USER: mwc
      POSTGRES_PASSWORD: mwc
      POSTGRES_DB: mwc
